### ISSUE TITLE
Add MonadTrans instance

### ISSUE THREAD

**Issue by phadej** [TomMD/monadcryptorandom#9]
Is there reason why they aren't defined? I can make a PR

**Comment by TomMD** [comment]
No reason, feel free to send a PR.  Bonus points if you set the right lower bound on MTL.

**Comment by phadej** [comment]
Hmm, I was somehow reading the docs very wrongly. It's already there. http://hackage.haskell.org/package/monadcryptorandom-0.7.0/docs/src/Control-Monad-CryptoRandom.html#line-306
